#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

echo "Starting TLS mounter ..."
cmd="exec voyager tls-mounter $TLS_MOUNTER_ARGS"
echo $cmd
$cmd
