/*
Copyright 2017 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1beta1

import (
	voyager_v1beta1 "github.com/appscode/voyager/apis/voyager/v1beta1"
	client "github.com/appscode/voyager/client"
	internalinterfaces "github.com/appscode/voyager/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/appscode/voyager/listers/voyager/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// CertificateInformer provides access to a shared informer and lister for
// Certificates.
type CertificateInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.CertificateLister
}

type certificateInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

func newCertificateInformer(client client.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	sharedIndexInformer := cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.VoyagerV1beta1().Certificates(v1.NamespaceAll).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.VoyagerV1beta1().Certificates(v1.NamespaceAll).Watch(options)
			},
		},
		&voyager_v1beta1.Certificate{},
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
	)

	return sharedIndexInformer
}

func (f *certificateInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&voyager_v1beta1.Certificate{}, newCertificateInformer)
}

func (f *certificateInformer) Lister() v1beta1.CertificateLister {
	return v1beta1.NewCertificateLister(f.Informer().GetIndexer())
}
