#!/bin/bash
set -eou pipefail

source /etc/envvars

HAPROXY_CONFIG=/etc/haproxy/haproxy.cfg
HAPROXY_PID=/var/run/haproxy.pid
HAPROXY_SOCK=/var/run/haproxy.sock

haproxy -c -f ${HAPROXY_CONFIG}

if [ -S ${HAPROXY_SOCK} ]; then
    echo "HAProxy hitless reloading..."
	haproxy -f ${HAPROXY_CONFIG} -p ${HAPROXY_PID} -x ${HAPROXY_SOCK} -sf $(cat ${HAPROXY_PID})
else
    echo "HAProxy soft reloading..."
	haproxy -f ${HAPROXY_CONFIG} -p ${HAPROXY_PID} -sf $(cat ${HAPROXY_PID})
fi
