#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})

source /etc/envvars

echo "Starting HAProxy controller ..."
cmd="exec voyager haproxy-controller $HAPROXY_CONTROLLER_ARGS"
echo $cmd
$cmd
