#!/bin/bash
exec 1> >(logger -s -p daemon.info -t ${PWD##*/})
exec 2> >(logger -s -p daemon.error -t ${PWD##*/})
source /etc/envvars

echo "Starting HAProxy configuration watcher and reloader ..."
exec /kloader --object='/etc/haproxy/haproxy.cfg' --boot-cmd='/etc/sv/reloader/reload' --v=5
