// +build !ignore_autogenerated

/*
Copyright 2017 The Stash Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1beta1

import (
	unsafe "unsafe"

	voyager "github.com/appscode/voyager/apis/voyager"
	core_v1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1beta1_ACMECertificateDetails_To_voyager_ACMECertificateDetails,
		Convert_voyager_ACMECertificateDetails_To_v1beta1_ACMECertificateDetails,
		Convert_v1beta1_AuthOption_To_voyager_AuthOption,
		Convert_voyager_AuthOption_To_v1beta1_AuthOption,
		Convert_v1beta1_BasicAuth_To_voyager_BasicAuth,
		Convert_voyager_BasicAuth_To_v1beta1_BasicAuth,
		Convert_v1beta1_Certificate_To_voyager_Certificate,
		Convert_voyager_Certificate_To_v1beta1_Certificate,
		Convert_v1beta1_CertificateCondition_To_voyager_CertificateCondition,
		Convert_voyager_CertificateCondition_To_v1beta1_CertificateCondition,
		Convert_v1beta1_CertificateDetails_To_voyager_CertificateDetails,
		Convert_voyager_CertificateDetails_To_v1beta1_CertificateDetails,
		Convert_v1beta1_CertificateList_To_voyager_CertificateList,
		Convert_voyager_CertificateList_To_v1beta1_CertificateList,
		Convert_v1beta1_CertificateSpec_To_voyager_CertificateSpec,
		Convert_voyager_CertificateSpec_To_v1beta1_CertificateSpec,
		Convert_v1beta1_CertificateStatus_To_voyager_CertificateStatus,
		Convert_voyager_CertificateStatus_To_v1beta1_CertificateStatus,
		Convert_v1beta1_CertificateStorage_To_voyager_CertificateStorage,
		Convert_voyager_CertificateStorage_To_v1beta1_CertificateStorage,
		Convert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider,
		Convert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider,
		Convert_v1beta1_DNSChallengeProvider_To_voyager_DNSChallengeProvider,
		Convert_voyager_DNSChallengeProvider_To_v1beta1_DNSChallengeProvider,
		Convert_v1beta1_FrontendRule_To_voyager_FrontendRule,
		Convert_voyager_FrontendRule_To_v1beta1_FrontendRule,
		Convert_v1beta1_HTTPChallengeProvider_To_voyager_HTTPChallengeProvider,
		Convert_voyager_HTTPChallengeProvider_To_v1beta1_HTTPChallengeProvider,
		Convert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend,
		Convert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend,
		Convert_v1beta1_HTTPIngressPath_To_voyager_HTTPIngressPath,
		Convert_voyager_HTTPIngressPath_To_v1beta1_HTTPIngressPath,
		Convert_v1beta1_HTTPIngressRuleValue_To_voyager_HTTPIngressRuleValue,
		Convert_voyager_HTTPIngressRuleValue_To_v1beta1_HTTPIngressRuleValue,
		Convert_v1beta1_Ingress_To_voyager_Ingress,
		Convert_voyager_Ingress_To_v1beta1_Ingress,
		Convert_v1beta1_IngressBackend_To_voyager_IngressBackend,
		Convert_voyager_IngressBackend_To_v1beta1_IngressBackend,
		Convert_v1beta1_IngressList_To_voyager_IngressList,
		Convert_voyager_IngressList_To_v1beta1_IngressList,
		Convert_v1beta1_IngressRef_To_voyager_IngressRef,
		Convert_voyager_IngressRef_To_v1beta1_IngressRef,
		Convert_v1beta1_IngressRule_To_voyager_IngressRule,
		Convert_voyager_IngressRule_To_v1beta1_IngressRule,
		Convert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue,
		Convert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue,
		Convert_v1beta1_IngressSpec_To_voyager_IngressSpec,
		Convert_voyager_IngressSpec_To_v1beta1_IngressSpec,
		Convert_v1beta1_IngressStatus_To_voyager_IngressStatus,
		Convert_voyager_IngressStatus_To_v1beta1_IngressStatus,
		Convert_v1beta1_IngressTLS_To_voyager_IngressTLS,
		Convert_voyager_IngressTLS_To_v1beta1_IngressTLS,
		Convert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference,
		Convert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference,
		Convert_v1beta1_TCPIngressRuleValue_To_voyager_TCPIngressRuleValue,
		Convert_voyager_TCPIngressRuleValue_To_v1beta1_TCPIngressRuleValue,
		Convert_v1beta1_TLSAuth_To_voyager_TLSAuth,
		Convert_voyager_TLSAuth_To_v1beta1_TLSAuth,
		Convert_v1beta1_VaultStore_To_voyager_VaultStore,
		Convert_voyager_VaultStore_To_v1beta1_VaultStore,
	)
}

func autoConvert_v1beta1_ACMECertificateDetails_To_voyager_ACMECertificateDetails(in *ACMECertificateDetails, out *voyager.ACMECertificateDetails, s conversion.Scope) error {
	out.Domain = in.Domain
	out.CertURL = in.CertURL
	out.CertStableURL = in.CertStableURL
	out.AccountRef = in.AccountRef
	return nil
}

// Convert_v1beta1_ACMECertificateDetails_To_voyager_ACMECertificateDetails is an autogenerated conversion function.
func Convert_v1beta1_ACMECertificateDetails_To_voyager_ACMECertificateDetails(in *ACMECertificateDetails, out *voyager.ACMECertificateDetails, s conversion.Scope) error {
	return autoConvert_v1beta1_ACMECertificateDetails_To_voyager_ACMECertificateDetails(in, out, s)
}

func autoConvert_voyager_ACMECertificateDetails_To_v1beta1_ACMECertificateDetails(in *voyager.ACMECertificateDetails, out *ACMECertificateDetails, s conversion.Scope) error {
	out.Domain = in.Domain
	out.CertURL = in.CertURL
	out.CertStableURL = in.CertStableURL
	out.AccountRef = in.AccountRef
	return nil
}

// Convert_voyager_ACMECertificateDetails_To_v1beta1_ACMECertificateDetails is an autogenerated conversion function.
func Convert_voyager_ACMECertificateDetails_To_v1beta1_ACMECertificateDetails(in *voyager.ACMECertificateDetails, out *ACMECertificateDetails, s conversion.Scope) error {
	return autoConvert_voyager_ACMECertificateDetails_To_v1beta1_ACMECertificateDetails(in, out, s)
}

func autoConvert_v1beta1_AuthOption_To_voyager_AuthOption(in *AuthOption, out *voyager.AuthOption, s conversion.Scope) error {
	out.Basic = (*voyager.BasicAuth)(unsafe.Pointer(in.Basic))
	out.TLS = (*voyager.TLSAuth)(unsafe.Pointer(in.TLS))
	return nil
}

// Convert_v1beta1_AuthOption_To_voyager_AuthOption is an autogenerated conversion function.
func Convert_v1beta1_AuthOption_To_voyager_AuthOption(in *AuthOption, out *voyager.AuthOption, s conversion.Scope) error {
	return autoConvert_v1beta1_AuthOption_To_voyager_AuthOption(in, out, s)
}

func autoConvert_voyager_AuthOption_To_v1beta1_AuthOption(in *voyager.AuthOption, out *AuthOption, s conversion.Scope) error {
	out.Basic = (*BasicAuth)(unsafe.Pointer(in.Basic))
	out.TLS = (*TLSAuth)(unsafe.Pointer(in.TLS))
	return nil
}

// Convert_voyager_AuthOption_To_v1beta1_AuthOption is an autogenerated conversion function.
func Convert_voyager_AuthOption_To_v1beta1_AuthOption(in *voyager.AuthOption, out *AuthOption, s conversion.Scope) error {
	return autoConvert_voyager_AuthOption_To_v1beta1_AuthOption(in, out, s)
}

func autoConvert_v1beta1_BasicAuth_To_voyager_BasicAuth(in *BasicAuth, out *voyager.BasicAuth, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.Realm = in.Realm
	return nil
}

// Convert_v1beta1_BasicAuth_To_voyager_BasicAuth is an autogenerated conversion function.
func Convert_v1beta1_BasicAuth_To_voyager_BasicAuth(in *BasicAuth, out *voyager.BasicAuth, s conversion.Scope) error {
	return autoConvert_v1beta1_BasicAuth_To_voyager_BasicAuth(in, out, s)
}

func autoConvert_voyager_BasicAuth_To_v1beta1_BasicAuth(in *voyager.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.Realm = in.Realm
	return nil
}

// Convert_voyager_BasicAuth_To_v1beta1_BasicAuth is an autogenerated conversion function.
func Convert_voyager_BasicAuth_To_v1beta1_BasicAuth(in *voyager.BasicAuth, out *BasicAuth, s conversion.Scope) error {
	return autoConvert_voyager_BasicAuth_To_v1beta1_BasicAuth(in, out, s)
}

func autoConvert_v1beta1_Certificate_To_voyager_Certificate(in *Certificate, out *voyager.Certificate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_CertificateSpec_To_voyager_CertificateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_CertificateStatus_To_voyager_CertificateStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Certificate_To_voyager_Certificate is an autogenerated conversion function.
func Convert_v1beta1_Certificate_To_voyager_Certificate(in *Certificate, out *voyager.Certificate, s conversion.Scope) error {
	return autoConvert_v1beta1_Certificate_To_voyager_Certificate(in, out, s)
}

func autoConvert_voyager_Certificate_To_v1beta1_Certificate(in *voyager.Certificate, out *Certificate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_voyager_CertificateSpec_To_v1beta1_CertificateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_voyager_CertificateStatus_To_v1beta1_CertificateStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_voyager_Certificate_To_v1beta1_Certificate is an autogenerated conversion function.
func Convert_voyager_Certificate_To_v1beta1_Certificate(in *voyager.Certificate, out *Certificate, s conversion.Scope) error {
	return autoConvert_voyager_Certificate_To_v1beta1_Certificate(in, out, s)
}

func autoConvert_v1beta1_CertificateCondition_To_voyager_CertificateCondition(in *CertificateCondition, out *voyager.CertificateCondition, s conversion.Scope) error {
	out.Type = voyager.RequestConditionType(in.Type)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_v1beta1_CertificateCondition_To_voyager_CertificateCondition is an autogenerated conversion function.
func Convert_v1beta1_CertificateCondition_To_voyager_CertificateCondition(in *CertificateCondition, out *voyager.CertificateCondition, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateCondition_To_voyager_CertificateCondition(in, out, s)
}

func autoConvert_voyager_CertificateCondition_To_v1beta1_CertificateCondition(in *voyager.CertificateCondition, out *CertificateCondition, s conversion.Scope) error {
	out.Type = RequestConditionType(in.Type)
	out.Reason = in.Reason
	out.Message = in.Message
	out.LastUpdateTime = in.LastUpdateTime
	return nil
}

// Convert_voyager_CertificateCondition_To_v1beta1_CertificateCondition is an autogenerated conversion function.
func Convert_voyager_CertificateCondition_To_v1beta1_CertificateCondition(in *voyager.CertificateCondition, out *CertificateCondition, s conversion.Scope) error {
	return autoConvert_voyager_CertificateCondition_To_v1beta1_CertificateCondition(in, out, s)
}

func autoConvert_v1beta1_CertificateDetails_To_voyager_CertificateDetails(in *CertificateDetails, out *voyager.CertificateDetails, s conversion.Scope) error {
	out.SerialNumber = in.SerialNumber
	out.NotBefore = in.NotBefore
	out.NotAfter = in.NotAfter
	out.CertURL = in.CertURL
	out.CertStableURL = in.CertStableURL
	out.AccountRef = in.AccountRef
	return nil
}

// Convert_v1beta1_CertificateDetails_To_voyager_CertificateDetails is an autogenerated conversion function.
func Convert_v1beta1_CertificateDetails_To_voyager_CertificateDetails(in *CertificateDetails, out *voyager.CertificateDetails, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateDetails_To_voyager_CertificateDetails(in, out, s)
}

func autoConvert_voyager_CertificateDetails_To_v1beta1_CertificateDetails(in *voyager.CertificateDetails, out *CertificateDetails, s conversion.Scope) error {
	out.SerialNumber = in.SerialNumber
	out.NotBefore = in.NotBefore
	out.NotAfter = in.NotAfter
	out.CertURL = in.CertURL
	out.CertStableURL = in.CertStableURL
	out.AccountRef = in.AccountRef
	return nil
}

// Convert_voyager_CertificateDetails_To_v1beta1_CertificateDetails is an autogenerated conversion function.
func Convert_voyager_CertificateDetails_To_v1beta1_CertificateDetails(in *voyager.CertificateDetails, out *CertificateDetails, s conversion.Scope) error {
	return autoConvert_voyager_CertificateDetails_To_v1beta1_CertificateDetails(in, out, s)
}

func autoConvert_v1beta1_CertificateList_To_voyager_CertificateList(in *CertificateList, out *voyager.CertificateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]voyager.Certificate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_CertificateList_To_voyager_CertificateList is an autogenerated conversion function.
func Convert_v1beta1_CertificateList_To_voyager_CertificateList(in *CertificateList, out *voyager.CertificateList, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateList_To_voyager_CertificateList(in, out, s)
}

func autoConvert_voyager_CertificateList_To_v1beta1_CertificateList(in *voyager.CertificateList, out *CertificateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Certificate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_voyager_CertificateList_To_v1beta1_CertificateList is an autogenerated conversion function.
func Convert_voyager_CertificateList_To_v1beta1_CertificateList(in *voyager.CertificateList, out *CertificateList, s conversion.Scope) error {
	return autoConvert_voyager_CertificateList_To_v1beta1_CertificateList(in, out, s)
}

func autoConvert_v1beta1_CertificateSpec_To_voyager_CertificateSpec(in *CertificateSpec, out *voyager.CertificateSpec, s conversion.Scope) error {
	out.Domains = *(*[]string)(unsafe.Pointer(&in.Domains))
	if err := Convert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider(&in.ChallengeProvider, &out.ChallengeProvider, s); err != nil {
		return err
	}
	out.ACMEUserSecretName = in.ACMEUserSecretName
	if err := Convert_v1beta1_CertificateStorage_To_voyager_CertificateStorage(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	out.Provider = in.Provider
	out.Email = in.Email
	if err := Convert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference(&in.HTTPProviderIngressReference, &out.HTTPProviderIngressReference, s); err != nil {
		return err
	}
	out.ProviderCredentialSecretName = in.ProviderCredentialSecretName
	out.ACMEServerURL = in.ACMEServerURL
	return nil
}

// Convert_v1beta1_CertificateSpec_To_voyager_CertificateSpec is an autogenerated conversion function.
func Convert_v1beta1_CertificateSpec_To_voyager_CertificateSpec(in *CertificateSpec, out *voyager.CertificateSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateSpec_To_voyager_CertificateSpec(in, out, s)
}

func autoConvert_voyager_CertificateSpec_To_v1beta1_CertificateSpec(in *voyager.CertificateSpec, out *CertificateSpec, s conversion.Scope) error {
	out.Domains = *(*[]string)(unsafe.Pointer(&in.Domains))
	if err := Convert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider(&in.ChallengeProvider, &out.ChallengeProvider, s); err != nil {
		return err
	}
	out.ACMEUserSecretName = in.ACMEUserSecretName
	if err := Convert_voyager_CertificateStorage_To_v1beta1_CertificateStorage(&in.Storage, &out.Storage, s); err != nil {
		return err
	}
	out.Provider = in.Provider
	out.Email = in.Email
	if err := Convert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference(&in.HTTPProviderIngressReference, &out.HTTPProviderIngressReference, s); err != nil {
		return err
	}
	out.ProviderCredentialSecretName = in.ProviderCredentialSecretName
	out.ACMEServerURL = in.ACMEServerURL
	return nil
}

// Convert_voyager_CertificateSpec_To_v1beta1_CertificateSpec is an autogenerated conversion function.
func Convert_voyager_CertificateSpec_To_v1beta1_CertificateSpec(in *voyager.CertificateSpec, out *CertificateSpec, s conversion.Scope) error {
	return autoConvert_voyager_CertificateSpec_To_v1beta1_CertificateSpec(in, out, s)
}

func autoConvert_v1beta1_CertificateStatus_To_voyager_CertificateStatus(in *CertificateStatus, out *voyager.CertificateStatus, s conversion.Scope) error {
	out.CreationTime = (*v1.Time)(unsafe.Pointer(in.CreationTime))
	out.Conditions = *(*[]voyager.CertificateCondition)(unsafe.Pointer(&in.Conditions))
	out.LastIssuedCertificate = (*voyager.CertificateDetails)(unsafe.Pointer(in.LastIssuedCertificate))
	out.CertificateObtained = in.CertificateObtained
	out.Message = in.Message
	out.ACMEUserSecretName = in.ACMEUserSecretName
	out.Details = (*voyager.ACMECertificateDetails)(unsafe.Pointer(in.Details))
	return nil
}

// Convert_v1beta1_CertificateStatus_To_voyager_CertificateStatus is an autogenerated conversion function.
func Convert_v1beta1_CertificateStatus_To_voyager_CertificateStatus(in *CertificateStatus, out *voyager.CertificateStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStatus_To_voyager_CertificateStatus(in, out, s)
}

func autoConvert_voyager_CertificateStatus_To_v1beta1_CertificateStatus(in *voyager.CertificateStatus, out *CertificateStatus, s conversion.Scope) error {
	out.CreationTime = (*v1.Time)(unsafe.Pointer(in.CreationTime))
	out.Conditions = *(*[]CertificateCondition)(unsafe.Pointer(&in.Conditions))
	out.LastIssuedCertificate = (*CertificateDetails)(unsafe.Pointer(in.LastIssuedCertificate))
	out.CertificateObtained = in.CertificateObtained
	out.Message = in.Message
	out.ACMEUserSecretName = in.ACMEUserSecretName
	out.Details = (*ACMECertificateDetails)(unsafe.Pointer(in.Details))
	return nil
}

// Convert_voyager_CertificateStatus_To_v1beta1_CertificateStatus is an autogenerated conversion function.
func Convert_voyager_CertificateStatus_To_v1beta1_CertificateStatus(in *voyager.CertificateStatus, out *CertificateStatus, s conversion.Scope) error {
	return autoConvert_voyager_CertificateStatus_To_v1beta1_CertificateStatus(in, out, s)
}

func autoConvert_v1beta1_CertificateStorage_To_voyager_CertificateStorage(in *CertificateStorage, out *voyager.CertificateStorage, s conversion.Scope) error {
	out.Secret = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.Secret))
	out.Vault = (*voyager.VaultStore)(unsafe.Pointer(in.Vault))
	return nil
}

// Convert_v1beta1_CertificateStorage_To_voyager_CertificateStorage is an autogenerated conversion function.
func Convert_v1beta1_CertificateStorage_To_voyager_CertificateStorage(in *CertificateStorage, out *voyager.CertificateStorage, s conversion.Scope) error {
	return autoConvert_v1beta1_CertificateStorage_To_voyager_CertificateStorage(in, out, s)
}

func autoConvert_voyager_CertificateStorage_To_v1beta1_CertificateStorage(in *voyager.CertificateStorage, out *CertificateStorage, s conversion.Scope) error {
	out.Secret = (*core_v1.LocalObjectReference)(unsafe.Pointer(in.Secret))
	out.Vault = (*VaultStore)(unsafe.Pointer(in.Vault))
	return nil
}

// Convert_voyager_CertificateStorage_To_v1beta1_CertificateStorage is an autogenerated conversion function.
func Convert_voyager_CertificateStorage_To_v1beta1_CertificateStorage(in *voyager.CertificateStorage, out *CertificateStorage, s conversion.Scope) error {
	return autoConvert_voyager_CertificateStorage_To_v1beta1_CertificateStorage(in, out, s)
}

func autoConvert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider(in *ChallengeProvider, out *voyager.ChallengeProvider, s conversion.Scope) error {
	out.HTTP = (*voyager.HTTPChallengeProvider)(unsafe.Pointer(in.HTTP))
	out.DNS = (*voyager.DNSChallengeProvider)(unsafe.Pointer(in.DNS))
	return nil
}

// Convert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider is an autogenerated conversion function.
func Convert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider(in *ChallengeProvider, out *voyager.ChallengeProvider, s conversion.Scope) error {
	return autoConvert_v1beta1_ChallengeProvider_To_voyager_ChallengeProvider(in, out, s)
}

func autoConvert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider(in *voyager.ChallengeProvider, out *ChallengeProvider, s conversion.Scope) error {
	out.HTTP = (*HTTPChallengeProvider)(unsafe.Pointer(in.HTTP))
	out.DNS = (*DNSChallengeProvider)(unsafe.Pointer(in.DNS))
	return nil
}

// Convert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider is an autogenerated conversion function.
func Convert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider(in *voyager.ChallengeProvider, out *ChallengeProvider, s conversion.Scope) error {
	return autoConvert_voyager_ChallengeProvider_To_v1beta1_ChallengeProvider(in, out, s)
}

func autoConvert_v1beta1_DNSChallengeProvider_To_voyager_DNSChallengeProvider(in *DNSChallengeProvider, out *voyager.DNSChallengeProvider, s conversion.Scope) error {
	out.Provider = in.Provider
	out.CredentialSecretName = in.CredentialSecretName
	return nil
}

// Convert_v1beta1_DNSChallengeProvider_To_voyager_DNSChallengeProvider is an autogenerated conversion function.
func Convert_v1beta1_DNSChallengeProvider_To_voyager_DNSChallengeProvider(in *DNSChallengeProvider, out *voyager.DNSChallengeProvider, s conversion.Scope) error {
	return autoConvert_v1beta1_DNSChallengeProvider_To_voyager_DNSChallengeProvider(in, out, s)
}

func autoConvert_voyager_DNSChallengeProvider_To_v1beta1_DNSChallengeProvider(in *voyager.DNSChallengeProvider, out *DNSChallengeProvider, s conversion.Scope) error {
	out.Provider = in.Provider
	out.CredentialSecretName = in.CredentialSecretName
	return nil
}

// Convert_voyager_DNSChallengeProvider_To_v1beta1_DNSChallengeProvider is an autogenerated conversion function.
func Convert_voyager_DNSChallengeProvider_To_v1beta1_DNSChallengeProvider(in *voyager.DNSChallengeProvider, out *DNSChallengeProvider, s conversion.Scope) error {
	return autoConvert_voyager_DNSChallengeProvider_To_v1beta1_DNSChallengeProvider(in, out, s)
}

func autoConvert_v1beta1_FrontendRule_To_voyager_FrontendRule(in *FrontendRule, out *voyager.FrontendRule, s conversion.Scope) error {
	out.Port = in.Port
	out.Rules = *(*[]string)(unsafe.Pointer(&in.Rules))
	out.Auth = (*voyager.AuthOption)(unsafe.Pointer(in.Auth))
	return nil
}

// Convert_v1beta1_FrontendRule_To_voyager_FrontendRule is an autogenerated conversion function.
func Convert_v1beta1_FrontendRule_To_voyager_FrontendRule(in *FrontendRule, out *voyager.FrontendRule, s conversion.Scope) error {
	return autoConvert_v1beta1_FrontendRule_To_voyager_FrontendRule(in, out, s)
}

func autoConvert_voyager_FrontendRule_To_v1beta1_FrontendRule(in *voyager.FrontendRule, out *FrontendRule, s conversion.Scope) error {
	out.Port = in.Port
	out.Rules = *(*[]string)(unsafe.Pointer(&in.Rules))
	out.Auth = (*AuthOption)(unsafe.Pointer(in.Auth))
	return nil
}

// Convert_voyager_FrontendRule_To_v1beta1_FrontendRule is an autogenerated conversion function.
func Convert_voyager_FrontendRule_To_v1beta1_FrontendRule(in *voyager.FrontendRule, out *FrontendRule, s conversion.Scope) error {
	return autoConvert_voyager_FrontendRule_To_v1beta1_FrontendRule(in, out, s)
}

func autoConvert_v1beta1_HTTPChallengeProvider_To_voyager_HTTPChallengeProvider(in *HTTPChallengeProvider, out *voyager.HTTPChallengeProvider, s conversion.Scope) error {
	if err := Convert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HTTPChallengeProvider_To_voyager_HTTPChallengeProvider is an autogenerated conversion function.
func Convert_v1beta1_HTTPChallengeProvider_To_voyager_HTTPChallengeProvider(in *HTTPChallengeProvider, out *voyager.HTTPChallengeProvider, s conversion.Scope) error {
	return autoConvert_v1beta1_HTTPChallengeProvider_To_voyager_HTTPChallengeProvider(in, out, s)
}

func autoConvert_voyager_HTTPChallengeProvider_To_v1beta1_HTTPChallengeProvider(in *voyager.HTTPChallengeProvider, out *HTTPChallengeProvider, s conversion.Scope) error {
	if err := Convert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference(&in.Ingress, &out.Ingress, s); err != nil {
		return err
	}
	return nil
}

// Convert_voyager_HTTPChallengeProvider_To_v1beta1_HTTPChallengeProvider is an autogenerated conversion function.
func Convert_voyager_HTTPChallengeProvider_To_v1beta1_HTTPChallengeProvider(in *voyager.HTTPChallengeProvider, out *HTTPChallengeProvider, s conversion.Scope) error {
	return autoConvert_voyager_HTTPChallengeProvider_To_v1beta1_HTTPChallengeProvider(in, out, s)
}

func autoConvert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend(in *HTTPIngressBackend, out *voyager.HTTPIngressBackend, s conversion.Scope) error {
	if err := Convert_v1beta1_IngressBackend_To_voyager_IngressBackend(&in.IngressBackend, &out.IngressBackend, s); err != nil {
		return err
	}
	out.RewriteRule = *(*[]string)(unsafe.Pointer(&in.RewriteRule))
	out.HeaderRule = *(*[]string)(unsafe.Pointer(&in.HeaderRule))
	return nil
}

// Convert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend is an autogenerated conversion function.
func Convert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend(in *HTTPIngressBackend, out *voyager.HTTPIngressBackend, s conversion.Scope) error {
	return autoConvert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend(in, out, s)
}

func autoConvert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend(in *voyager.HTTPIngressBackend, out *HTTPIngressBackend, s conversion.Scope) error {
	if err := Convert_voyager_IngressBackend_To_v1beta1_IngressBackend(&in.IngressBackend, &out.IngressBackend, s); err != nil {
		return err
	}
	out.RewriteRule = *(*[]string)(unsafe.Pointer(&in.RewriteRule))
	out.HeaderRule = *(*[]string)(unsafe.Pointer(&in.HeaderRule))
	return nil
}

// Convert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend is an autogenerated conversion function.
func Convert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend(in *voyager.HTTPIngressBackend, out *HTTPIngressBackend, s conversion.Scope) error {
	return autoConvert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend(in, out, s)
}

func autoConvert_v1beta1_HTTPIngressPath_To_voyager_HTTPIngressPath(in *HTTPIngressPath, out *voyager.HTTPIngressPath, s conversion.Scope) error {
	out.Path = in.Path
	if err := Convert_v1beta1_HTTPIngressBackend_To_voyager_HTTPIngressBackend(&in.Backend, &out.Backend, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_HTTPIngressPath_To_voyager_HTTPIngressPath is an autogenerated conversion function.
func Convert_v1beta1_HTTPIngressPath_To_voyager_HTTPIngressPath(in *HTTPIngressPath, out *voyager.HTTPIngressPath, s conversion.Scope) error {
	return autoConvert_v1beta1_HTTPIngressPath_To_voyager_HTTPIngressPath(in, out, s)
}

func autoConvert_voyager_HTTPIngressPath_To_v1beta1_HTTPIngressPath(in *voyager.HTTPIngressPath, out *HTTPIngressPath, s conversion.Scope) error {
	out.Path = in.Path
	if err := Convert_voyager_HTTPIngressBackend_To_v1beta1_HTTPIngressBackend(&in.Backend, &out.Backend, s); err != nil {
		return err
	}
	return nil
}

// Convert_voyager_HTTPIngressPath_To_v1beta1_HTTPIngressPath is an autogenerated conversion function.
func Convert_voyager_HTTPIngressPath_To_v1beta1_HTTPIngressPath(in *voyager.HTTPIngressPath, out *HTTPIngressPath, s conversion.Scope) error {
	return autoConvert_voyager_HTTPIngressPath_To_v1beta1_HTTPIngressPath(in, out, s)
}

func autoConvert_v1beta1_HTTPIngressRuleValue_To_voyager_HTTPIngressRuleValue(in *HTTPIngressRuleValue, out *voyager.HTTPIngressRuleValue, s conversion.Scope) error {
	out.Port = in.Port
	out.NoTLS = in.NoTLS
	out.NodePort = in.NodePort
	out.Paths = *(*[]voyager.HTTPIngressPath)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_v1beta1_HTTPIngressRuleValue_To_voyager_HTTPIngressRuleValue is an autogenerated conversion function.
func Convert_v1beta1_HTTPIngressRuleValue_To_voyager_HTTPIngressRuleValue(in *HTTPIngressRuleValue, out *voyager.HTTPIngressRuleValue, s conversion.Scope) error {
	return autoConvert_v1beta1_HTTPIngressRuleValue_To_voyager_HTTPIngressRuleValue(in, out, s)
}

func autoConvert_voyager_HTTPIngressRuleValue_To_v1beta1_HTTPIngressRuleValue(in *voyager.HTTPIngressRuleValue, out *HTTPIngressRuleValue, s conversion.Scope) error {
	out.Port = in.Port
	out.NoTLS = in.NoTLS
	out.NodePort = in.NodePort
	out.Paths = *(*[]HTTPIngressPath)(unsafe.Pointer(&in.Paths))
	return nil
}

// Convert_voyager_HTTPIngressRuleValue_To_v1beta1_HTTPIngressRuleValue is an autogenerated conversion function.
func Convert_voyager_HTTPIngressRuleValue_To_v1beta1_HTTPIngressRuleValue(in *voyager.HTTPIngressRuleValue, out *HTTPIngressRuleValue, s conversion.Scope) error {
	return autoConvert_voyager_HTTPIngressRuleValue_To_v1beta1_HTTPIngressRuleValue(in, out, s)
}

func autoConvert_v1beta1_Ingress_To_voyager_Ingress(in *Ingress, out *voyager.Ingress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_IngressSpec_To_voyager_IngressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_IngressStatus_To_voyager_IngressStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_Ingress_To_voyager_Ingress is an autogenerated conversion function.
func Convert_v1beta1_Ingress_To_voyager_Ingress(in *Ingress, out *voyager.Ingress, s conversion.Scope) error {
	return autoConvert_v1beta1_Ingress_To_voyager_Ingress(in, out, s)
}

func autoConvert_voyager_Ingress_To_v1beta1_Ingress(in *voyager.Ingress, out *Ingress, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_voyager_IngressSpec_To_v1beta1_IngressSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_voyager_IngressStatus_To_v1beta1_IngressStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_voyager_Ingress_To_v1beta1_Ingress is an autogenerated conversion function.
func Convert_voyager_Ingress_To_v1beta1_Ingress(in *voyager.Ingress, out *Ingress, s conversion.Scope) error {
	return autoConvert_voyager_Ingress_To_v1beta1_Ingress(in, out, s)
}

func autoConvert_v1beta1_IngressBackend_To_voyager_IngressBackend(in *IngressBackend, out *voyager.IngressBackend, s conversion.Scope) error {
	out.HostNames = *(*[]string)(unsafe.Pointer(&in.HostNames))
	out.ServiceName = in.ServiceName
	out.ServicePort = in.ServicePort
	out.BackendRule = *(*[]string)(unsafe.Pointer(&in.BackendRule))
	return nil
}

// Convert_v1beta1_IngressBackend_To_voyager_IngressBackend is an autogenerated conversion function.
func Convert_v1beta1_IngressBackend_To_voyager_IngressBackend(in *IngressBackend, out *voyager.IngressBackend, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressBackend_To_voyager_IngressBackend(in, out, s)
}

func autoConvert_voyager_IngressBackend_To_v1beta1_IngressBackend(in *voyager.IngressBackend, out *IngressBackend, s conversion.Scope) error {
	out.HostNames = *(*[]string)(unsafe.Pointer(&in.HostNames))
	out.ServiceName = in.ServiceName
	out.ServicePort = in.ServicePort
	out.BackendRule = *(*[]string)(unsafe.Pointer(&in.BackendRule))
	return nil
}

// Convert_voyager_IngressBackend_To_v1beta1_IngressBackend is an autogenerated conversion function.
func Convert_voyager_IngressBackend_To_v1beta1_IngressBackend(in *voyager.IngressBackend, out *IngressBackend, s conversion.Scope) error {
	return autoConvert_voyager_IngressBackend_To_v1beta1_IngressBackend(in, out, s)
}

func autoConvert_v1beta1_IngressList_To_voyager_IngressList(in *IngressList, out *voyager.IngressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]voyager.Ingress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1beta1_IngressList_To_voyager_IngressList is an autogenerated conversion function.
func Convert_v1beta1_IngressList_To_voyager_IngressList(in *IngressList, out *voyager.IngressList, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressList_To_voyager_IngressList(in, out, s)
}

func autoConvert_voyager_IngressList_To_v1beta1_IngressList(in *voyager.IngressList, out *IngressList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Ingress)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_voyager_IngressList_To_v1beta1_IngressList is an autogenerated conversion function.
func Convert_voyager_IngressList_To_v1beta1_IngressList(in *voyager.IngressList, out *IngressList, s conversion.Scope) error {
	return autoConvert_voyager_IngressList_To_v1beta1_IngressList(in, out, s)
}

func autoConvert_v1beta1_IngressRef_To_voyager_IngressRef(in *IngressRef, out *voyager.IngressRef, s conversion.Scope) error {
	out.APISchema = in.APISchema
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1beta1_IngressRef_To_voyager_IngressRef is an autogenerated conversion function.
func Convert_v1beta1_IngressRef_To_voyager_IngressRef(in *IngressRef, out *voyager.IngressRef, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressRef_To_voyager_IngressRef(in, out, s)
}

func autoConvert_voyager_IngressRef_To_v1beta1_IngressRef(in *voyager.IngressRef, out *IngressRef, s conversion.Scope) error {
	out.APISchema = in.APISchema
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_voyager_IngressRef_To_v1beta1_IngressRef is an autogenerated conversion function.
func Convert_voyager_IngressRef_To_v1beta1_IngressRef(in *voyager.IngressRef, out *IngressRef, s conversion.Scope) error {
	return autoConvert_voyager_IngressRef_To_v1beta1_IngressRef(in, out, s)
}

func autoConvert_v1beta1_IngressRule_To_voyager_IngressRule(in *IngressRule, out *voyager.IngressRule, s conversion.Scope) error {
	out.Host = in.Host
	if err := Convert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue(&in.IngressRuleValue, &out.IngressRuleValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_IngressRule_To_voyager_IngressRule is an autogenerated conversion function.
func Convert_v1beta1_IngressRule_To_voyager_IngressRule(in *IngressRule, out *voyager.IngressRule, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressRule_To_voyager_IngressRule(in, out, s)
}

func autoConvert_voyager_IngressRule_To_v1beta1_IngressRule(in *voyager.IngressRule, out *IngressRule, s conversion.Scope) error {
	out.Host = in.Host
	if err := Convert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue(&in.IngressRuleValue, &out.IngressRuleValue, s); err != nil {
		return err
	}
	return nil
}

// Convert_voyager_IngressRule_To_v1beta1_IngressRule is an autogenerated conversion function.
func Convert_voyager_IngressRule_To_v1beta1_IngressRule(in *voyager.IngressRule, out *IngressRule, s conversion.Scope) error {
	return autoConvert_voyager_IngressRule_To_v1beta1_IngressRule(in, out, s)
}

func autoConvert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue(in *IngressRuleValue, out *voyager.IngressRuleValue, s conversion.Scope) error {
	out.HTTP = (*voyager.HTTPIngressRuleValue)(unsafe.Pointer(in.HTTP))
	out.TCP = (*voyager.TCPIngressRuleValue)(unsafe.Pointer(in.TCP))
	return nil
}

// Convert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue is an autogenerated conversion function.
func Convert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue(in *IngressRuleValue, out *voyager.IngressRuleValue, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressRuleValue_To_voyager_IngressRuleValue(in, out, s)
}

func autoConvert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue(in *voyager.IngressRuleValue, out *IngressRuleValue, s conversion.Scope) error {
	out.HTTP = (*HTTPIngressRuleValue)(unsafe.Pointer(in.HTTP))
	out.TCP = (*TCPIngressRuleValue)(unsafe.Pointer(in.TCP))
	return nil
}

// Convert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue is an autogenerated conversion function.
func Convert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue(in *voyager.IngressRuleValue, out *IngressRuleValue, s conversion.Scope) error {
	return autoConvert_voyager_IngressRuleValue_To_v1beta1_IngressRuleValue(in, out, s)
}

func autoConvert_v1beta1_IngressSpec_To_voyager_IngressSpec(in *IngressSpec, out *voyager.IngressSpec, s conversion.Scope) error {
	out.Backend = (*voyager.HTTPIngressBackend)(unsafe.Pointer(in.Backend))
	out.TLS = *(*[]voyager.IngressTLS)(unsafe.Pointer(&in.TLS))
	out.FrontendRules = *(*[]voyager.FrontendRule)(unsafe.Pointer(&in.FrontendRules))
	out.Rules = *(*[]voyager.IngressRule)(unsafe.Pointer(&in.Rules))
	out.LoadBalancerSourceRanges = *(*[]string)(unsafe.Pointer(&in.LoadBalancerSourceRanges))
	out.Resources = in.Resources
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.SchedulerName = in.SchedulerName
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_v1beta1_IngressSpec_To_voyager_IngressSpec is an autogenerated conversion function.
func Convert_v1beta1_IngressSpec_To_voyager_IngressSpec(in *IngressSpec, out *voyager.IngressSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressSpec_To_voyager_IngressSpec(in, out, s)
}

func autoConvert_voyager_IngressSpec_To_v1beta1_IngressSpec(in *voyager.IngressSpec, out *IngressSpec, s conversion.Scope) error {
	out.Backend = (*HTTPIngressBackend)(unsafe.Pointer(in.Backend))
	out.TLS = *(*[]IngressTLS)(unsafe.Pointer(&in.TLS))
	out.FrontendRules = *(*[]FrontendRule)(unsafe.Pointer(&in.FrontendRules))
	out.Rules = *(*[]IngressRule)(unsafe.Pointer(&in.Rules))
	out.LoadBalancerSourceRanges = *(*[]string)(unsafe.Pointer(&in.LoadBalancerSourceRanges))
	out.Resources = in.Resources
	out.Affinity = (*core_v1.Affinity)(unsafe.Pointer(in.Affinity))
	out.SchedulerName = in.SchedulerName
	out.Tolerations = *(*[]core_v1.Toleration)(unsafe.Pointer(&in.Tolerations))
	return nil
}

// Convert_voyager_IngressSpec_To_v1beta1_IngressSpec is an autogenerated conversion function.
func Convert_voyager_IngressSpec_To_v1beta1_IngressSpec(in *voyager.IngressSpec, out *IngressSpec, s conversion.Scope) error {
	return autoConvert_voyager_IngressSpec_To_v1beta1_IngressSpec(in, out, s)
}

func autoConvert_v1beta1_IngressStatus_To_voyager_IngressStatus(in *IngressStatus, out *voyager.IngressStatus, s conversion.Scope) error {
	out.LoadBalancer = in.LoadBalancer
	return nil
}

// Convert_v1beta1_IngressStatus_To_voyager_IngressStatus is an autogenerated conversion function.
func Convert_v1beta1_IngressStatus_To_voyager_IngressStatus(in *IngressStatus, out *voyager.IngressStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressStatus_To_voyager_IngressStatus(in, out, s)
}

func autoConvert_voyager_IngressStatus_To_v1beta1_IngressStatus(in *voyager.IngressStatus, out *IngressStatus, s conversion.Scope) error {
	out.LoadBalancer = in.LoadBalancer
	return nil
}

// Convert_voyager_IngressStatus_To_v1beta1_IngressStatus is an autogenerated conversion function.
func Convert_voyager_IngressStatus_To_v1beta1_IngressStatus(in *voyager.IngressStatus, out *IngressStatus, s conversion.Scope) error {
	return autoConvert_voyager_IngressStatus_To_v1beta1_IngressStatus(in, out, s)
}

func autoConvert_v1beta1_IngressTLS_To_voyager_IngressTLS(in *IngressTLS, out *voyager.IngressTLS, s conversion.Scope) error {
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	out.SecretName = in.SecretName
	out.Ref = (*voyager.LocalTypedReference)(unsafe.Pointer(in.Ref))
	return nil
}

// Convert_v1beta1_IngressTLS_To_voyager_IngressTLS is an autogenerated conversion function.
func Convert_v1beta1_IngressTLS_To_voyager_IngressTLS(in *IngressTLS, out *voyager.IngressTLS, s conversion.Scope) error {
	return autoConvert_v1beta1_IngressTLS_To_voyager_IngressTLS(in, out, s)
}

func autoConvert_voyager_IngressTLS_To_v1beta1_IngressTLS(in *voyager.IngressTLS, out *IngressTLS, s conversion.Scope) error {
	out.Hosts = *(*[]string)(unsafe.Pointer(&in.Hosts))
	out.SecretName = in.SecretName
	out.Ref = (*LocalTypedReference)(unsafe.Pointer(in.Ref))
	return nil
}

// Convert_voyager_IngressTLS_To_v1beta1_IngressTLS is an autogenerated conversion function.
func Convert_voyager_IngressTLS_To_v1beta1_IngressTLS(in *voyager.IngressTLS, out *IngressTLS, s conversion.Scope) error {
	return autoConvert_voyager_IngressTLS_To_v1beta1_IngressTLS(in, out, s)
}

func autoConvert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference(in *LocalTypedReference, out *voyager.LocalTypedReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	out.APIVersion = in.APIVersion
	out.ResourceVersion = in.ResourceVersion
	return nil
}

// Convert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference is an autogenerated conversion function.
func Convert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference(in *LocalTypedReference, out *voyager.LocalTypedReference, s conversion.Scope) error {
	return autoConvert_v1beta1_LocalTypedReference_To_voyager_LocalTypedReference(in, out, s)
}

func autoConvert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference(in *voyager.LocalTypedReference, out *LocalTypedReference, s conversion.Scope) error {
	out.Kind = in.Kind
	out.Name = in.Name
	out.UID = types.UID(in.UID)
	out.APIVersion = in.APIVersion
	out.ResourceVersion = in.ResourceVersion
	return nil
}

// Convert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference is an autogenerated conversion function.
func Convert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference(in *voyager.LocalTypedReference, out *LocalTypedReference, s conversion.Scope) error {
	return autoConvert_voyager_LocalTypedReference_To_v1beta1_LocalTypedReference(in, out, s)
}

func autoConvert_v1beta1_TCPIngressRuleValue_To_voyager_TCPIngressRuleValue(in *TCPIngressRuleValue, out *voyager.TCPIngressRuleValue, s conversion.Scope) error {
	out.Port = in.Port
	out.NoTLS = in.NoTLS
	out.NodePort = in.NodePort
	if err := Convert_v1beta1_IngressBackend_To_voyager_IngressBackend(&in.Backend, &out.Backend, s); err != nil {
		return err
	}
	out.ALPN = *(*[]string)(unsafe.Pointer(&in.ALPN))
	return nil
}

// Convert_v1beta1_TCPIngressRuleValue_To_voyager_TCPIngressRuleValue is an autogenerated conversion function.
func Convert_v1beta1_TCPIngressRuleValue_To_voyager_TCPIngressRuleValue(in *TCPIngressRuleValue, out *voyager.TCPIngressRuleValue, s conversion.Scope) error {
	return autoConvert_v1beta1_TCPIngressRuleValue_To_voyager_TCPIngressRuleValue(in, out, s)
}

func autoConvert_voyager_TCPIngressRuleValue_To_v1beta1_TCPIngressRuleValue(in *voyager.TCPIngressRuleValue, out *TCPIngressRuleValue, s conversion.Scope) error {
	out.Port = in.Port
	out.NoTLS = in.NoTLS
	out.NodePort = in.NodePort
	if err := Convert_voyager_IngressBackend_To_v1beta1_IngressBackend(&in.Backend, &out.Backend, s); err != nil {
		return err
	}
	out.ALPN = *(*[]string)(unsafe.Pointer(&in.ALPN))
	return nil
}

// Convert_voyager_TCPIngressRuleValue_To_v1beta1_TCPIngressRuleValue is an autogenerated conversion function.
func Convert_voyager_TCPIngressRuleValue_To_v1beta1_TCPIngressRuleValue(in *voyager.TCPIngressRuleValue, out *TCPIngressRuleValue, s conversion.Scope) error {
	return autoConvert_voyager_TCPIngressRuleValue_To_v1beta1_TCPIngressRuleValue(in, out, s)
}

func autoConvert_v1beta1_TLSAuth_To_voyager_TLSAuth(in *TLSAuth, out *voyager.TLSAuth, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.VerifyClient = voyager.TLSAuthVerifyOption(in.VerifyClient)
	out.Headers = *(*map[string]string)(unsafe.Pointer(&in.Headers))
	out.ErrorPage = in.ErrorPage
	return nil
}

// Convert_v1beta1_TLSAuth_To_voyager_TLSAuth is an autogenerated conversion function.
func Convert_v1beta1_TLSAuth_To_voyager_TLSAuth(in *TLSAuth, out *voyager.TLSAuth, s conversion.Scope) error {
	return autoConvert_v1beta1_TLSAuth_To_voyager_TLSAuth(in, out, s)
}

func autoConvert_voyager_TLSAuth_To_v1beta1_TLSAuth(in *voyager.TLSAuth, out *TLSAuth, s conversion.Scope) error {
	out.SecretName = in.SecretName
	out.VerifyClient = TLSAuthVerifyOption(in.VerifyClient)
	out.Headers = *(*map[string]string)(unsafe.Pointer(&in.Headers))
	out.ErrorPage = in.ErrorPage
	return nil
}

// Convert_voyager_TLSAuth_To_v1beta1_TLSAuth is an autogenerated conversion function.
func Convert_voyager_TLSAuth_To_v1beta1_TLSAuth(in *voyager.TLSAuth, out *TLSAuth, s conversion.Scope) error {
	return autoConvert_voyager_TLSAuth_To_v1beta1_TLSAuth(in, out, s)
}

func autoConvert_v1beta1_VaultStore_To_voyager_VaultStore(in *VaultStore, out *voyager.VaultStore, s conversion.Scope) error {
	out.Name = in.Name
	out.Prefix = in.Prefix
	return nil
}

// Convert_v1beta1_VaultStore_To_voyager_VaultStore is an autogenerated conversion function.
func Convert_v1beta1_VaultStore_To_voyager_VaultStore(in *VaultStore, out *voyager.VaultStore, s conversion.Scope) error {
	return autoConvert_v1beta1_VaultStore_To_voyager_VaultStore(in, out, s)
}

func autoConvert_voyager_VaultStore_To_v1beta1_VaultStore(in *voyager.VaultStore, out *VaultStore, s conversion.Scope) error {
	out.Name = in.Name
	out.Prefix = in.Prefix
	return nil
}

// Convert_voyager_VaultStore_To_v1beta1_VaultStore is an autogenerated conversion function.
func Convert_voyager_VaultStore_To_v1beta1_VaultStore(in *voyager.VaultStore, out *VaultStore, s conversion.Scope) error {
	return autoConvert_voyager_VaultStore_To_v1beta1_VaultStore(in, out, s)
}
