apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: voyager
  name: certificates.voyager.appscode.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domains[0]
    name: Domains
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: voyager.appscode.com
  names:
    categories:
    - networking
    - appscode
    - all
    kind: Certificate
    listKind: CertificateList
    plural: certificates
    shortNames:
    - cert
    singular: certificate
  preserveUnknownFields: false
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            acmeUserSecretName:
              description: 'Secret contains ACMEUser information. Secret must contain
                a key `email` If empty tries to find an Secret via domains if not
                found create an ACMEUser and stores as a secret. Secrets key to be
                expected:  ACME_EMAIL -> required, if not provided it will through
                error.  ACME_SERVER_URL -> custom server url to generate certificates,
                default is lets encrypt.  ACME_USER_DATA -> user data, if not found
                one will be created for the provided email,    and stored in the key.'
              type: string
            challengeProvider:
              description: ChallengeProvider details to verify domains
              properties:
                dns:
                  properties:
                    credentialSecretName:
                      type: string
                    provider:
                      description: DNS Provider from the list https://github.com/appscode/voyager/blob/master/docs/tasks/certificate/providers.md
                      type: string
                  type: object
                http:
                  properties:
                    ingress:
                      description: LocalTypedReference contains enough information
                        to let you inspect or modify the referred object.
                      properties:
                        apiVersion:
                          description: API version of the referent.
                          type: string
                        kind:
                          description: 'Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                          type: string
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names'
                          type: string
                      type: object
                  type: object
              type: object
            domains:
              description: Tries to obtain a single certificate using all domains
                passed into Domains. The first domain in domains is used for the CommonName
                field of the certificate, all other domains are added using the Subject
                Alternate Names extension.
              items:
                type: string
              type: array
            paused:
              description: Indicates that the certificate is paused.
              type: boolean
            renewalBufferDays:
              description: Configure certificate renewal buffer period in days. Default
                15 days.
              format: int32
              type: integer
            storage:
              description: Storage backend to store the certificates currently, kubernetes
                secret and vault.
              properties:
                secret:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                vault:
                  properties:
                    name:
                      type: string
                    prefix:
                      type: string
                  type: object
              type: object
          required:
          - acmeUserSecretName
          - challengeProvider
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastUpdateTime:
                    description: timestamp for the last update to this condition
                    format: date-time
                    type: string
                  message:
                    description: human readable message with details about the request
                      state
                    type: string
                  reason:
                    description: brief reason for the request state
                    type: string
                  type:
                    description: request approval state, currently Approved or Denied.
                    type: string
                required:
                - type
                type: object
              type: array
            creationTime:
              format: date-time
              type: string
            lastIssuedCertificate:
              properties:
                accountRef:
                  type: string
                certStableURL:
                  type: string
                certURL:
                  type: string
                notAfter:
                  format: date-time
                  type: string
                notBefore:
                  format: date-time
                  type: string
                serialNumber:
                  type: string
              required:
              - certStableURL
              - certURL
              type: object
            observedGeneration:
              description: observedGeneration is the most recent generation observed
                for this resource. It corresponds to the resource's generation, which
                is updated on mutation by the API Server.
              format: int64
              type: integer
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
