# Copyright AppsCode Inc. and Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:buster

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN true

RUN set -x \
  && apt-get update \
  && apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl

RUN set -x \
  && curl -fsSL -o auth-request.lua https://raw.githubusercontent.com/appscode/haproxy-auth-request/v{ARG_HAPROXY}/auth-request.lua



FROM {ARG_FROM}

RUN set -x \
  && apk add --update --no-cache ca-certificates lua5.3 lua-socket \
  && ln -sf /usr/share/lua/ /usr/local/share/ \
  && ln -sf /usr/lib/lua/ /usr/local/lib/

COPY --from=0 /auth-request.lua /etc/auth-request.lua
COPY hack/docker/voyager/templates /srv/voyager/templates/
ADD  bin/{ARG_OS}_{ARG_ARCH}/{ARG_BIN} /{ARG_BIN}

# https://github.com/voyagermesh/voyager/pull/1038
COPY hack/docker/voyager/test.pem /etc/ssl/private/haproxy/tls/test.pem
COPY hack/docker/voyager/errorfiles /srv/voyager/errorfiles/

ENTRYPOINT ["/{ARG_BIN}"]
