name: release-tracker

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Generate LGTM App token
        id: lgtm-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.LGTM_APP_CLIENT_ID }}
          private-key: ${{ secrets.LGTM_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: CHANGELOG
          permission-pull-requests: write

      - name: Update release tracker
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ steps.lgtm-app-token.outputs.token }}
        run: |
          ./hack/scripts/update-release-tracker.sh
